# Generated by Django 3.1.2 on 2020-10-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='https://photogallery-project.s3-us-west-1.amazonaws.com/static/', max_length=50),
            preserve_default=False,
        ),
    ]
