# Generated by Django 3.1.2 on 2020-10-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
